// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/status-service/status-service.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace SnackTime.MediaServer.Service.Status {
  public static partial class Status
  {
    static readonly string __ServiceName = "snacktime.status.service.Status";

    static readonly grpc::Marshaller<global::SnackTime.MediaServer.Service.Status.PingRequest> __Marshaller_snacktime_status_service_PingRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SnackTime.MediaServer.Service.Status.PingRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SnackTime.MediaServer.Service.Status.PingResponse> __Marshaller_snacktime_status_service_PingResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SnackTime.MediaServer.Service.Status.PingResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::SnackTime.MediaServer.Service.Status.PingRequest, global::SnackTime.MediaServer.Service.Status.PingResponse> __Method_Ping = new grpc::Method<global::SnackTime.MediaServer.Service.Status.PingRequest, global::SnackTime.MediaServer.Service.Status.PingResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Ping",
        __Marshaller_snacktime_status_service_PingRequest,
        __Marshaller_snacktime_status_service_PingResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::SnackTime.MediaServer.Service.Status.StatusServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Status</summary>
    public abstract partial class StatusBase
    {
      public virtual global::System.Threading.Tasks.Task<global::SnackTime.MediaServer.Service.Status.PingResponse> Ping(global::SnackTime.MediaServer.Service.Status.PingRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Status</summary>
    public partial class StatusClient : grpc::ClientBase<StatusClient>
    {
      /// <summary>Creates a new client for Status</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public StatusClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Status that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public StatusClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected StatusClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected StatusClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::SnackTime.MediaServer.Service.Status.PingResponse Ping(global::SnackTime.MediaServer.Service.Status.PingRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Ping(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::SnackTime.MediaServer.Service.Status.PingResponse Ping(global::SnackTime.MediaServer.Service.Status.PingRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Ping, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::SnackTime.MediaServer.Service.Status.PingResponse> PingAsync(global::SnackTime.MediaServer.Service.Status.PingRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PingAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::SnackTime.MediaServer.Service.Status.PingResponse> PingAsync(global::SnackTime.MediaServer.Service.Status.PingRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Ping, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override StatusClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new StatusClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(StatusBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Ping, serviceImpl.Ping).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, StatusBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Ping, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::SnackTime.MediaServer.Service.Status.PingRequest, global::SnackTime.MediaServer.Service.Status.PingResponse>(serviceImpl.Ping));
    }

  }
}
#endregion
