// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/episode-service/episode-getRecommendedBySeriesIdRequest.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SnackTime.MediaServer.Service.Episode {

  /// <summary>Holder for reflection information generated from proto/episode-service/episode-getRecommendedBySeriesIdRequest.proto</summary>
  public static partial class EpisodeGetRecommendedBySeriesIdRequestReflection {

    #region Descriptor
    /// <summary>File descriptor for proto/episode-service/episode-getRecommendedBySeriesIdRequest.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EpisodeGetRecommendedBySeriesIdRequestReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CkNwcm90by9lcGlzb2RlLXNlcnZpY2UvZXBpc29kZS1nZXRSZWNvbW1lbmRl",
            "ZEJ5U2VyaWVzSWRSZXF1ZXN0LnByb3RvEhlzbmFja3RpbWUuZXBpc29kZS5z",
            "ZXJ2aWNlGhFwcm90by9tZWRpYS5wcm90byIzCh9HZXRSZWNvbW1lbmRlZEJ5",
            "U2VyaWVzSWRSZXF1ZXN0EhAKCHNlcmllc0lkGAEgASgFIk0KIEdldFJlY29t",
            "bWVuZGVkQnlTZXJpZXNJZFJlc3BvbnNlEikKB2VwaXNvZGUYASABKAsyGC5z",
            "bmFja3RpbWUubWVkaWEuRXBpc29kZUIoqgIlU25hY2tUaW1lLk1lZGlhU2Vy",
            "dmVyLlNlcnZpY2UuRXBpc29kZWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::SnackTime.MediaServer.Models.ProtoGenerated.MediaReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::SnackTime.MediaServer.Service.Episode.GetRecommendedBySeriesIdRequest), global::SnackTime.MediaServer.Service.Episode.GetRecommendedBySeriesIdRequest.Parser, new[]{ "SeriesId" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SnackTime.MediaServer.Service.Episode.GetRecommendedBySeriesIdResponse), global::SnackTime.MediaServer.Service.Episode.GetRecommendedBySeriesIdResponse.Parser, new[]{ "Episode" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class GetRecommendedBySeriesIdRequest : pb::IMessage<GetRecommendedBySeriesIdRequest> {
    private static readonly pb::MessageParser<GetRecommendedBySeriesIdRequest> _parser = new pb::MessageParser<GetRecommendedBySeriesIdRequest>(() => new GetRecommendedBySeriesIdRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetRecommendedBySeriesIdRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SnackTime.MediaServer.Service.Episode.EpisodeGetRecommendedBySeriesIdRequestReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetRecommendedBySeriesIdRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetRecommendedBySeriesIdRequest(GetRecommendedBySeriesIdRequest other) : this() {
      seriesId_ = other.seriesId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetRecommendedBySeriesIdRequest Clone() {
      return new GetRecommendedBySeriesIdRequest(this);
    }

    /// <summary>Field number for the "seriesId" field.</summary>
    public const int SeriesIdFieldNumber = 1;
    private int seriesId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int SeriesId {
      get { return seriesId_; }
      set {
        seriesId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetRecommendedBySeriesIdRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetRecommendedBySeriesIdRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SeriesId != other.SeriesId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (SeriesId != 0) hash ^= SeriesId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (SeriesId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(SeriesId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (SeriesId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SeriesId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetRecommendedBySeriesIdRequest other) {
      if (other == null) {
        return;
      }
      if (other.SeriesId != 0) {
        SeriesId = other.SeriesId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            SeriesId = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class GetRecommendedBySeriesIdResponse : pb::IMessage<GetRecommendedBySeriesIdResponse> {
    private static readonly pb::MessageParser<GetRecommendedBySeriesIdResponse> _parser = new pb::MessageParser<GetRecommendedBySeriesIdResponse>(() => new GetRecommendedBySeriesIdResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetRecommendedBySeriesIdResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SnackTime.MediaServer.Service.Episode.EpisodeGetRecommendedBySeriesIdRequestReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetRecommendedBySeriesIdResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetRecommendedBySeriesIdResponse(GetRecommendedBySeriesIdResponse other) : this() {
      episode_ = other.episode_ != null ? other.episode_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetRecommendedBySeriesIdResponse Clone() {
      return new GetRecommendedBySeriesIdResponse(this);
    }

    /// <summary>Field number for the "episode" field.</summary>
    public const int EpisodeFieldNumber = 1;
    private global::SnackTime.MediaServer.Models.ProtoGenerated.Episode episode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::SnackTime.MediaServer.Models.ProtoGenerated.Episode Episode {
      get { return episode_; }
      set {
        episode_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetRecommendedBySeriesIdResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetRecommendedBySeriesIdResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Episode, other.Episode)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (episode_ != null) hash ^= Episode.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (episode_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Episode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (episode_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Episode);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetRecommendedBySeriesIdResponse other) {
      if (other == null) {
        return;
      }
      if (other.episode_ != null) {
        if (episode_ == null) {
          episode_ = new global::SnackTime.MediaServer.Models.ProtoGenerated.Episode();
        }
        Episode.MergeFrom(other.Episode);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (episode_ == null) {
              episode_ = new global::SnackTime.MediaServer.Models.ProtoGenerated.Episode();
            }
            input.ReadMessage(episode_);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
