// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/episode-service/episode-service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SnackTime.MediaServer.Service.Episode {

  /// <summary>Holder for reflection information generated from proto/episode-service/episode-service.proto</summary>
  public static partial class EpisodeServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for proto/episode-service/episode-service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EpisodeServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Citwcm90by9lcGlzb2RlLXNlcnZpY2UvZXBpc29kZS1zZXJ2aWNlLnByb3Rv",
            "EhlzbmFja3RpbWUuZXBpc29kZS5zZXJ2aWNlGitwcm90by9lcGlzb2RlLXNl",
            "cnZpY2UvZXBpc29kZS1nZXRCeUlkLnByb3RvGjFwcm90by9lcGlzb2RlLXNl",
            "cnZpY2UvZXBpc29kZS1nZXRCeVNlcmllc0lkLnByb3RvMuMBCgdFcGlzb2Rl",
            "EnQKDUdldEJ5U2VyaWVzSWQSLy5zbmFja3RpbWUuZXBpc29kZS5zZXJ2aWNl",
            "LkdldEJ5U2VyaWVzSWRSZXF1ZXN0GjAuc25hY2t0aW1lLmVwaXNvZGUuc2Vy",
            "dmljZS5HZXRCeVNlcmllc0lkUmVzcG9uc2UiABJiCgdHZXRCeUlkEikuc25h",
            "Y2t0aW1lLmVwaXNvZGUuc2VydmljZS5HZXRCeUlkUmVxdWVzdBoqLnNuYWNr",
            "dGltZS5lcGlzb2RlLnNlcnZpY2UuR2V0QnlJZFJlc3BvbnNlIgBCKKoCJVNu",
            "YWNrVGltZS5NZWRpYVNlcnZlci5TZXJ2aWNlLkVwaXNvZGViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::SnackTime.MediaServer.Service.Episode.EpisodeGetByIdReflection.Descriptor, global::SnackTime.MediaServer.Service.Episode.EpisodeGetBySeriesIdReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
