// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/file-service/file-service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SnackTime.MediaServer.Service.File {

  /// <summary>Holder for reflection information generated from proto/file-service/file-service.proto</summary>
  public static partial class FileServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for proto/file-service/file-service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static FileServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiVwcm90by9maWxlLXNlcnZpY2UvZmlsZS1zZXJ2aWNlLnByb3RvEhZzbmFj",
            "a3RpbWUuZmlsZS5zZXJ2aWNlGiZwcm90by9maWxlLXNlcnZpY2UvZmlsZS1k",
            "b3dubG9hZC5wcm90bzJxCgRGaWxlEmkKCERvd25sb2FkEisuc25hY2t0aW1l",
            "LmZpbGUuc2VydmljZS5Eb3dubG9hZEZpbGVSZXF1ZXN0Giwuc25hY2t0aW1l",
            "LmZpbGUuc2VydmljZS5SZXNwb25zZURvd25sb2FkRmlsZSIAMAFCJaoCIlNu",
            "YWNrVGltZS5NZWRpYVNlcnZlci5TZXJ2aWNlLkZpbGViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::SnackTime.MediaServer.Service.File.FileDownloadReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
