// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/file-service/file-service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SnackTime.MediaServer.Service.File {

  /// <summary>Holder for reflection information generated from proto/file-service/file-service.proto</summary>
  public static partial class FileServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for proto/file-service/file-service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static FileServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiVwcm90by9maWxlLXNlcnZpY2UvZmlsZS1zZXJ2aWNlLnByb3RvEhVzbmFj",
            "a3RpbWUuc2VyaWVzLmZpbGUaJnByb3RvL2ZpbGUtc2VydmljZS9maWxlLWRv",
            "d25sb2FkLnByb3RvMm8KBEZpbGUSZwoIRG93bmxvYWQSKi5zbmFja3RpbWUu",
            "c2VyaWVzLmZpbGUuRG93bmxvYWRGaWxlUmVxdWVzdBorLnNuYWNrdGltZS5z",
            "ZXJpZXMuZmlsZS5SZXNwb25zZURvd25sb2FkRmlsZSIAMAFCJaoCIlNuYWNr",
            "VGltZS5NZWRpYVNlcnZlci5TZXJ2aWNlLkZpbGViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::SnackTime.MediaServer.Service.File.FileDownloadReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
