// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/series-service/series-service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SnackTime.MediaServer.Service.Series {

  /// <summary>Holder for reflection information generated from proto/series-service/series-service.proto</summary>
  public static partial class SeriesServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for proto/series-service/series-service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SeriesServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cilwcm90by9zZXJpZXMtc2VydmljZS9zZXJpZXMtc2VydmljZS5wcm90bxIY",
            "c25hY2t0aW1lLnNlcmllcy5zZXJ2aWNlGjNwcm90by9zZXJpZXMtc2Vydmlj",
            "ZS9zZXJpZXMtZ2V0TGFzdERvd25sb2FkZWQucHJvdG8aKHByb3RvL3Nlcmll",
            "cy1zZXJ2aWNlL3Nlcmllcy1nZXRBbGwucHJvdG8aKXByb3RvL3Nlcmllcy1z",
            "ZXJ2aWNlL3Nlcmllcy1nZXRCeUlkLnByb3RvMskCCgZTZXJpZXMSfgoRR2V0",
            "TGFzdERvd25sb2FkZWQSMi5zbmFja3RpbWUuc2VyaWVzLnNlcnZpY2UuR2V0",
            "TGFzdERvd25sb2FkZWRSZXF1ZXN0GjMuc25hY2t0aW1lLnNlcmllcy5zZXJ2",
            "aWNlLkdldExhc3REb3dubG9hZGVkUmVzcG9uc2UiABJdCgZHZXRBbGwSJy5z",
            "bmFja3RpbWUuc2VyaWVzLnNlcnZpY2UuR2V0QWxsUmVxdWVzdBooLnNuYWNr",
            "dGltZS5zZXJpZXMuc2VydmljZS5HZXRBbGxSZXNwb25zZSIAEmAKB0dldEJ5",
            "SWQSKC5zbmFja3RpbWUuc2VyaWVzLnNlcnZpY2UuR2V0QnlJZFJlcXVlc3Qa",
            "KS5zbmFja3RpbWUuc2VyaWVzLnNlcnZpY2UuR2V0QnlJZFJlc3BvbnNlIgBC",
            "J6oCJFNuYWNrVGltZS5NZWRpYVNlcnZlci5TZXJ2aWNlLlNlcmllc2IGcHJv",
            "dG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::SnackTime.MediaServer.Service.Series.SeriesGetLastDownloadedReflection.Descriptor, global::SnackTime.MediaServer.Service.Series.SeriesGetAllReflection.Descriptor, global::SnackTime.MediaServer.Service.Series.SeriesGetByIdReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
