// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/serssion-service/session-service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SnackTime.MediaServer.Service.Session {

  /// <summary>Holder for reflection information generated from proto/serssion-service/session-service.proto</summary>
  public static partial class SessionServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for proto/serssion-service/session-service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SessionServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cixwcm90by9zZXJzc2lvbi1zZXJ2aWNlL3Nlc3Npb24tc2VydmljZS5wcm90",
            "bxIYc25hY2t0aW1lLnNlcmllcy5zZXNzaW9uGitwcm90by9zZXJzc2lvbi1z",
            "ZXJ2aWNlL3Nlc3Npb24tZ2V0QWxsLnByb3RvGitwcm90by9zZXJzc2lvbi1z",
            "ZXJ2aWNlL3Nlc3Npb24tdXBzZXJ0LnByb3RvMscBCgdTZXNzaW9uEl0KBkdl",
            "dEFsbBInLnNuYWNrdGltZS5zZXJpZXMuc2Vzc2lvbi5HZXRBbGxSZXF1ZXN0",
            "Giguc25hY2t0aW1lLnNlcmllcy5zZXNzaW9uLkdldEFsbFJlc3BvbnNlIgAS",
            "XQoGVXBzZXJ0Eicuc25hY2t0aW1lLnNlcmllcy5zZXNzaW9uLlVwc2VydFJl",
            "cXVlc3QaKC5zbmFja3RpbWUuc2VyaWVzLnNlc3Npb24uVXBzZXJ0UmVzcG9u",
            "c2UiAEIoqgIlU25hY2tUaW1lLk1lZGlhU2VydmVyLlNlcnZpY2UuU2Vzc2lv",
            "bmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::SnackTime.MediaServer.Service.Session.SessionGetAllReflection.Descriptor, global::SnackTime.MediaServer.Service.Session.SessionUpsertReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
