// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/status-service/status-service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SnackTime.MediaServer.Service.Status {

  /// <summary>Holder for reflection information generated from proto/status-service/status-service.proto</summary>
  public static partial class StatusServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for proto/status-service/status-service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StatusServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cilwcm90by9zdGF0dXMtc2VydmljZS9zdGF0dXMtc2VydmljZS5wcm90bxIY",
            "c25hY2t0aW1lLnN0YXR1cy5zZXJ2aWNlGiZwcm90by9zdGF0dXMtc2Vydmlj",
            "ZS9zdGF0dXMtcGluZy5wcm90bzJhCgZTdGF0dXMSVwoEUGluZxIlLnNuYWNr",
            "dGltZS5zdGF0dXMuc2VydmljZS5QaW5nUmVxdWVzdBomLnNuYWNrdGltZS5z",
            "dGF0dXMuc2VydmljZS5QaW5nUmVzcG9uc2UiAEInqgIkU25hY2tUaW1lLk1l",
            "ZGlhU2VydmVyLlNlcnZpY2UuU3RhdHVzYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::SnackTime.MediaServer.Service.Status.StatusPingReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
