// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/storage.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SnackTime.MediaServer.Storage.ProtoGenerated {

  /// <summary>Holder for reflection information generated from proto/storage.proto</summary>
  public static partial class StorageReflection {

    #region Descriptor
    /// <summary>File descriptor for proto/storage.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StorageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNwcm90by9zdG9yYWdlLnByb3RvEhFzbmFja3RpbWUuc3RvcmFnZSJfCglN",
            "ZWRpYUZpbGUSEAoIZmlsZU5hbWUYASABKAkSEQoJbWVkaWFOYW1lGAIgASgJ",
            "EhUKDWRvd25sb2FkZWRVVEMYAyABKAkSFgoObGFzdFdhdGNoZWRVVEMYBCAB",
            "KAkitQEKB1Nlc3Npb24SCgoCaWQYASABKAkSEAoIc3RhcnRVVEMYAiABKAMS",
            "DgoGZW5kVVRDGAMgASgDEg8KB21lZGlhSWQYBCABKAkSDgoGZmlsZUlkGAUg",
            "ASgJEi0KCGR1cmF0aW9uGAYgASgLMhsuc25hY2t0aW1lLnN0b3JhZ2UuRHVy",
            "YXRpb24SGAoQbWVkaWFMZW5naHRJblNlYxgHIAEoARISCgpmcm9tRGV2aWNl",
            "GAggASgJIj4KCER1cmF0aW9uEhkKEXN0YXJ0UG9zdGlvbkluU2VjGAEgASgB",
            "EhcKD2VuZFBvc3Rpb25JblNlYxgCIAEoASJICghQcm9ncmVzcxIUCgx3YXRj",
            "aGVkSW5TZWMYASABKAESDgoGbGVuZ2h0GAIgASgBEhYKDmxhc3RXYXRjaGVk",
            "VXRjGAMgASgBQi+qAixTbmFja1RpbWUuTWVkaWFTZXJ2ZXIuU3RvcmFnZS5Q",
            "cm90b0dlbmVyYXRlZGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::SnackTime.MediaServer.Storage.ProtoGenerated.MediaFile), global::SnackTime.MediaServer.Storage.ProtoGenerated.MediaFile.Parser, new[]{ "FileName", "MediaName", "DownloadedUTC", "LastWatchedUTC" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SnackTime.MediaServer.Storage.ProtoGenerated.Session), global::SnackTime.MediaServer.Storage.ProtoGenerated.Session.Parser, new[]{ "Id", "StartUTC", "EndUTC", "MediaId", "FileId", "Duration", "MediaLenghtInSec", "FromDevice" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SnackTime.MediaServer.Storage.ProtoGenerated.Duration), global::SnackTime.MediaServer.Storage.ProtoGenerated.Duration.Parser, new[]{ "StartPostionInSec", "EndPostionInSec" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SnackTime.MediaServer.Storage.ProtoGenerated.Progress), global::SnackTime.MediaServer.Storage.ProtoGenerated.Progress.Parser, new[]{ "WatchedInSec", "Lenght", "LastWatchedUtc" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class MediaFile : pb::IMessage<MediaFile> {
    private static readonly pb::MessageParser<MediaFile> _parser = new pb::MessageParser<MediaFile>(() => new MediaFile());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MediaFile> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SnackTime.MediaServer.Storage.ProtoGenerated.StorageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MediaFile() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MediaFile(MediaFile other) : this() {
      fileName_ = other.fileName_;
      mediaName_ = other.mediaName_;
      downloadedUTC_ = other.downloadedUTC_;
      lastWatchedUTC_ = other.lastWatchedUTC_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MediaFile Clone() {
      return new MediaFile(this);
    }

    /// <summary>Field number for the "fileName" field.</summary>
    public const int FileNameFieldNumber = 1;
    private string fileName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string FileName {
      get { return fileName_; }
      set {
        fileName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "mediaName" field.</summary>
    public const int MediaNameFieldNumber = 2;
    private string mediaName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string MediaName {
      get { return mediaName_; }
      set {
        mediaName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "downloadedUTC" field.</summary>
    public const int DownloadedUTCFieldNumber = 3;
    private string downloadedUTC_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string DownloadedUTC {
      get { return downloadedUTC_; }
      set {
        downloadedUTC_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "lastWatchedUTC" field.</summary>
    public const int LastWatchedUTCFieldNumber = 4;
    private string lastWatchedUTC_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string LastWatchedUTC {
      get { return lastWatchedUTC_; }
      set {
        lastWatchedUTC_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MediaFile);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MediaFile other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (FileName != other.FileName) return false;
      if (MediaName != other.MediaName) return false;
      if (DownloadedUTC != other.DownloadedUTC) return false;
      if (LastWatchedUTC != other.LastWatchedUTC) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (FileName.Length != 0) hash ^= FileName.GetHashCode();
      if (MediaName.Length != 0) hash ^= MediaName.GetHashCode();
      if (DownloadedUTC.Length != 0) hash ^= DownloadedUTC.GetHashCode();
      if (LastWatchedUTC.Length != 0) hash ^= LastWatchedUTC.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (FileName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(FileName);
      }
      if (MediaName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(MediaName);
      }
      if (DownloadedUTC.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(DownloadedUTC);
      }
      if (LastWatchedUTC.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(LastWatchedUTC);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (FileName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FileName);
      }
      if (MediaName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MediaName);
      }
      if (DownloadedUTC.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DownloadedUTC);
      }
      if (LastWatchedUTC.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LastWatchedUTC);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MediaFile other) {
      if (other == null) {
        return;
      }
      if (other.FileName.Length != 0) {
        FileName = other.FileName;
      }
      if (other.MediaName.Length != 0) {
        MediaName = other.MediaName;
      }
      if (other.DownloadedUTC.Length != 0) {
        DownloadedUTC = other.DownloadedUTC;
      }
      if (other.LastWatchedUTC.Length != 0) {
        LastWatchedUTC = other.LastWatchedUTC;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            FileName = input.ReadString();
            break;
          }
          case 18: {
            MediaName = input.ReadString();
            break;
          }
          case 26: {
            DownloadedUTC = input.ReadString();
            break;
          }
          case 34: {
            LastWatchedUTC = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class Session : pb::IMessage<Session> {
    private static readonly pb::MessageParser<Session> _parser = new pb::MessageParser<Session>(() => new Session());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Session> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SnackTime.MediaServer.Storage.ProtoGenerated.StorageReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Session() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Session(Session other) : this() {
      id_ = other.id_;
      startUTC_ = other.startUTC_;
      endUTC_ = other.endUTC_;
      mediaId_ = other.mediaId_;
      fileId_ = other.fileId_;
      duration_ = other.duration_ != null ? other.duration_.Clone() : null;
      mediaLenghtInSec_ = other.mediaLenghtInSec_;
      fromDevice_ = other.fromDevice_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Session Clone() {
      return new Session(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "startUTC" field.</summary>
    public const int StartUTCFieldNumber = 2;
    private long startUTC_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long StartUTC {
      get { return startUTC_; }
      set {
        startUTC_ = value;
      }
    }

    /// <summary>Field number for the "endUTC" field.</summary>
    public const int EndUTCFieldNumber = 3;
    private long endUTC_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long EndUTC {
      get { return endUTC_; }
      set {
        endUTC_ = value;
      }
    }

    /// <summary>Field number for the "mediaId" field.</summary>
    public const int MediaIdFieldNumber = 4;
    private string mediaId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string MediaId {
      get { return mediaId_; }
      set {
        mediaId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "fileId" field.</summary>
    public const int FileIdFieldNumber = 5;
    private string fileId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string FileId {
      get { return fileId_; }
      set {
        fileId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "duration" field.</summary>
    public const int DurationFieldNumber = 6;
    private global::SnackTime.MediaServer.Storage.ProtoGenerated.Duration duration_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::SnackTime.MediaServer.Storage.ProtoGenerated.Duration Duration {
      get { return duration_; }
      set {
        duration_ = value;
      }
    }

    /// <summary>Field number for the "mediaLenghtInSec" field.</summary>
    public const int MediaLenghtInSecFieldNumber = 7;
    private double mediaLenghtInSec_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double MediaLenghtInSec {
      get { return mediaLenghtInSec_; }
      set {
        mediaLenghtInSec_ = value;
      }
    }

    /// <summary>Field number for the "fromDevice" field.</summary>
    public const int FromDeviceFieldNumber = 8;
    private string fromDevice_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string FromDevice {
      get { return fromDevice_; }
      set {
        fromDevice_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Session);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Session other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (StartUTC != other.StartUTC) return false;
      if (EndUTC != other.EndUTC) return false;
      if (MediaId != other.MediaId) return false;
      if (FileId != other.FileId) return false;
      if (!object.Equals(Duration, other.Duration)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(MediaLenghtInSec, other.MediaLenghtInSec)) return false;
      if (FromDevice != other.FromDevice) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (StartUTC != 0L) hash ^= StartUTC.GetHashCode();
      if (EndUTC != 0L) hash ^= EndUTC.GetHashCode();
      if (MediaId.Length != 0) hash ^= MediaId.GetHashCode();
      if (FileId.Length != 0) hash ^= FileId.GetHashCode();
      if (duration_ != null) hash ^= Duration.GetHashCode();
      if (MediaLenghtInSec != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(MediaLenghtInSec);
      if (FromDevice.Length != 0) hash ^= FromDevice.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (StartUTC != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(StartUTC);
      }
      if (EndUTC != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(EndUTC);
      }
      if (MediaId.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(MediaId);
      }
      if (FileId.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(FileId);
      }
      if (duration_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Duration);
      }
      if (MediaLenghtInSec != 0D) {
        output.WriteRawTag(57);
        output.WriteDouble(MediaLenghtInSec);
      }
      if (FromDevice.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(FromDevice);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (StartUTC != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(StartUTC);
      }
      if (EndUTC != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(EndUTC);
      }
      if (MediaId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MediaId);
      }
      if (FileId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FileId);
      }
      if (duration_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Duration);
      }
      if (MediaLenghtInSec != 0D) {
        size += 1 + 8;
      }
      if (FromDevice.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FromDevice);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Session other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.StartUTC != 0L) {
        StartUTC = other.StartUTC;
      }
      if (other.EndUTC != 0L) {
        EndUTC = other.EndUTC;
      }
      if (other.MediaId.Length != 0) {
        MediaId = other.MediaId;
      }
      if (other.FileId.Length != 0) {
        FileId = other.FileId;
      }
      if (other.duration_ != null) {
        if (duration_ == null) {
          duration_ = new global::SnackTime.MediaServer.Storage.ProtoGenerated.Duration();
        }
        Duration.MergeFrom(other.Duration);
      }
      if (other.MediaLenghtInSec != 0D) {
        MediaLenghtInSec = other.MediaLenghtInSec;
      }
      if (other.FromDevice.Length != 0) {
        FromDevice = other.FromDevice;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 16: {
            StartUTC = input.ReadInt64();
            break;
          }
          case 24: {
            EndUTC = input.ReadInt64();
            break;
          }
          case 34: {
            MediaId = input.ReadString();
            break;
          }
          case 42: {
            FileId = input.ReadString();
            break;
          }
          case 50: {
            if (duration_ == null) {
              duration_ = new global::SnackTime.MediaServer.Storage.ProtoGenerated.Duration();
            }
            input.ReadMessage(duration_);
            break;
          }
          case 57: {
            MediaLenghtInSec = input.ReadDouble();
            break;
          }
          case 66: {
            FromDevice = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class Duration : pb::IMessage<Duration> {
    private static readonly pb::MessageParser<Duration> _parser = new pb::MessageParser<Duration>(() => new Duration());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Duration> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SnackTime.MediaServer.Storage.ProtoGenerated.StorageReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Duration() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Duration(Duration other) : this() {
      startPostionInSec_ = other.startPostionInSec_;
      endPostionInSec_ = other.endPostionInSec_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Duration Clone() {
      return new Duration(this);
    }

    /// <summary>Field number for the "startPostionInSec" field.</summary>
    public const int StartPostionInSecFieldNumber = 1;
    private double startPostionInSec_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double StartPostionInSec {
      get { return startPostionInSec_; }
      set {
        startPostionInSec_ = value;
      }
    }

    /// <summary>Field number for the "endPostionInSec" field.</summary>
    public const int EndPostionInSecFieldNumber = 2;
    private double endPostionInSec_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double EndPostionInSec {
      get { return endPostionInSec_; }
      set {
        endPostionInSec_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Duration);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Duration other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(StartPostionInSec, other.StartPostionInSec)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(EndPostionInSec, other.EndPostionInSec)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (StartPostionInSec != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(StartPostionInSec);
      if (EndPostionInSec != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(EndPostionInSec);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (StartPostionInSec != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(StartPostionInSec);
      }
      if (EndPostionInSec != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(EndPostionInSec);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (StartPostionInSec != 0D) {
        size += 1 + 8;
      }
      if (EndPostionInSec != 0D) {
        size += 1 + 8;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Duration other) {
      if (other == null) {
        return;
      }
      if (other.StartPostionInSec != 0D) {
        StartPostionInSec = other.StartPostionInSec;
      }
      if (other.EndPostionInSec != 0D) {
        EndPostionInSec = other.EndPostionInSec;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 9: {
            StartPostionInSec = input.ReadDouble();
            break;
          }
          case 17: {
            EndPostionInSec = input.ReadDouble();
            break;
          }
        }
      }
    }

  }

  public sealed partial class Progress : pb::IMessage<Progress> {
    private static readonly pb::MessageParser<Progress> _parser = new pb::MessageParser<Progress>(() => new Progress());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Progress> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SnackTime.MediaServer.Storage.ProtoGenerated.StorageReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Progress() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Progress(Progress other) : this() {
      watchedInSec_ = other.watchedInSec_;
      lenght_ = other.lenght_;
      lastWatchedUtc_ = other.lastWatchedUtc_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Progress Clone() {
      return new Progress(this);
    }

    /// <summary>Field number for the "watchedInSec" field.</summary>
    public const int WatchedInSecFieldNumber = 1;
    private double watchedInSec_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double WatchedInSec {
      get { return watchedInSec_; }
      set {
        watchedInSec_ = value;
      }
    }

    /// <summary>Field number for the "lenght" field.</summary>
    public const int LenghtFieldNumber = 2;
    private double lenght_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double Lenght {
      get { return lenght_; }
      set {
        lenght_ = value;
      }
    }

    /// <summary>Field number for the "lastWatchedUtc" field.</summary>
    public const int LastWatchedUtcFieldNumber = 3;
    private double lastWatchedUtc_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double LastWatchedUtc {
      get { return lastWatchedUtc_; }
      set {
        lastWatchedUtc_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Progress);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Progress other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(WatchedInSec, other.WatchedInSec)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Lenght, other.Lenght)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(LastWatchedUtc, other.LastWatchedUtc)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (WatchedInSec != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(WatchedInSec);
      if (Lenght != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Lenght);
      if (LastWatchedUtc != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(LastWatchedUtc);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (WatchedInSec != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(WatchedInSec);
      }
      if (Lenght != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(Lenght);
      }
      if (LastWatchedUtc != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(LastWatchedUtc);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (WatchedInSec != 0D) {
        size += 1 + 8;
      }
      if (Lenght != 0D) {
        size += 1 + 8;
      }
      if (LastWatchedUtc != 0D) {
        size += 1 + 8;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Progress other) {
      if (other == null) {
        return;
      }
      if (other.WatchedInSec != 0D) {
        WatchedInSec = other.WatchedInSec;
      }
      if (other.Lenght != 0D) {
        Lenght = other.Lenght;
      }
      if (other.LastWatchedUtc != 0D) {
        LastWatchedUtc = other.LastWatchedUtc;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 9: {
            WatchedInSec = input.ReadDouble();
            break;
          }
          case 17: {
            Lenght = input.ReadDouble();
            break;
          }
          case 25: {
            LastWatchedUtc = input.ReadDouble();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
