// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/storage.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SnackTime.MediaServer.Storage.ProtoGenerated {

  /// <summary>Holder for reflection information generated from proto/storage.proto</summary>
  public static partial class StorageReflection {

    #region Descriptor
    /// <summary>File descriptor for proto/storage.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StorageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNwcm90by9zdG9yYWdlLnByb3RvEhFzbmFja3RpbWUuc3RvcmFnZSJfCglN",
            "ZWRpYUZpbGUSEAoIZmlsZU5hbWUYASABKAkSEQoJbWVkaWFOYW1lGAIgASgJ",
            "EhUKDWRvd25sb2FkZWRVVEMYAyABKAkSFgoObGFzdFdhdGNoZWRVVEMYBCAB",
            "KAlCL6oCLFNuYWNrVGltZS5NZWRpYVNlcnZlci5TdG9yYWdlLlByb3RvR2Vu",
            "ZXJhdGVkYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::SnackTime.MediaServer.Storage.ProtoGenerated.MediaFile), global::SnackTime.MediaServer.Storage.ProtoGenerated.MediaFile.Parser, new[]{ "FileName", "MediaName", "DownloadedUTC", "LastWatchedUTC" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class MediaFile : pb::IMessage<MediaFile> {
    private static readonly pb::MessageParser<MediaFile> _parser = new pb::MessageParser<MediaFile>(() => new MediaFile());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MediaFile> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SnackTime.MediaServer.Storage.ProtoGenerated.StorageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MediaFile() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MediaFile(MediaFile other) : this() {
      fileName_ = other.fileName_;
      mediaName_ = other.mediaName_;
      downloadedUTC_ = other.downloadedUTC_;
      lastWatchedUTC_ = other.lastWatchedUTC_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MediaFile Clone() {
      return new MediaFile(this);
    }

    /// <summary>Field number for the "fileName" field.</summary>
    public const int FileNameFieldNumber = 1;
    private string fileName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string FileName {
      get { return fileName_; }
      set {
        fileName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "mediaName" field.</summary>
    public const int MediaNameFieldNumber = 2;
    private string mediaName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string MediaName {
      get { return mediaName_; }
      set {
        mediaName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "downloadedUTC" field.</summary>
    public const int DownloadedUTCFieldNumber = 3;
    private string downloadedUTC_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string DownloadedUTC {
      get { return downloadedUTC_; }
      set {
        downloadedUTC_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "lastWatchedUTC" field.</summary>
    public const int LastWatchedUTCFieldNumber = 4;
    private string lastWatchedUTC_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string LastWatchedUTC {
      get { return lastWatchedUTC_; }
      set {
        lastWatchedUTC_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MediaFile);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MediaFile other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (FileName != other.FileName) return false;
      if (MediaName != other.MediaName) return false;
      if (DownloadedUTC != other.DownloadedUTC) return false;
      if (LastWatchedUTC != other.LastWatchedUTC) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (FileName.Length != 0) hash ^= FileName.GetHashCode();
      if (MediaName.Length != 0) hash ^= MediaName.GetHashCode();
      if (DownloadedUTC.Length != 0) hash ^= DownloadedUTC.GetHashCode();
      if (LastWatchedUTC.Length != 0) hash ^= LastWatchedUTC.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (FileName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(FileName);
      }
      if (MediaName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(MediaName);
      }
      if (DownloadedUTC.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(DownloadedUTC);
      }
      if (LastWatchedUTC.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(LastWatchedUTC);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (FileName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FileName);
      }
      if (MediaName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MediaName);
      }
      if (DownloadedUTC.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DownloadedUTC);
      }
      if (LastWatchedUTC.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LastWatchedUTC);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MediaFile other) {
      if (other == null) {
        return;
      }
      if (other.FileName.Length != 0) {
        FileName = other.FileName;
      }
      if (other.MediaName.Length != 0) {
        MediaName = other.MediaName;
      }
      if (other.DownloadedUTC.Length != 0) {
        DownloadedUTC = other.DownloadedUTC;
      }
      if (other.LastWatchedUTC.Length != 0) {
        LastWatchedUTC = other.LastWatchedUTC;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            FileName = input.ReadString();
            break;
          }
          case 18: {
            MediaName = input.ReadString();
            break;
          }
          case 26: {
            DownloadedUTC = input.ReadString();
            break;
          }
          case 34: {
            LastWatchedUTC = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
